---

# -------------------------------------------------------------------------------------------------
# Job Name
# -------------------------------------------------------------------------------------------------
name: build


# -------------------------------------------------------------------------------------------------
# When to run
# -------------------------------------------------------------------------------------------------
on:
  push:
#    paths:
#      - 'Makefile'
#      - 'Dockerfiles/**'
#      - 'tests/**'
#      - '.github/workflows/action*.yml'
#      - '.github/workflows/params.yml'

jobs:

  # -----------------------------------------------------------------------------------------------
  # (1/8) Determine parameter settings
  # -----------------------------------------------------------------------------------------------
  params:
    uses: ./.github/workflows/params.yml

  # -----------------------------------------------------------------------------------------------
  # (2/8) Configure Build and Deploy Matrices
  # -----------------------------------------------------------------------------------------------
  configure:
    needs: [params]
    uses: devilbox/github-actions/.github/workflows/docker-multistage-configure.yml@master
    with:
      enabled: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' || (github.event_name == 'pull_request' && (github.event.pull_request.user.login != 'cytopia')) }}
      can_deploy: ${{ (github.repository == 'cytopia/docker-ansible') && (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/') || startsWith(github.ref, 'refs/heads/release-')) }}
      is_scheduled: false
      versions: ${{ needs.params.outputs.versions }}
      refs: ${{ needs.params.outputs.refs }}
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}


  # -----------------------------------------------------------------------------------------------
  # (3/8) Build & Test builder
  # -----------------------------------------------------------------------------------------------
  #  build-builder:
  #    needs:
  #      - params
  #      - configure
  #    uses: devilbox/github-actions/.github/workflows/docker-multistage-build.yml@master
  #    with:
  #      has_refs: ${{ needs.configure.outputs.has_refs == 'true' }}
  #      run_tests: false
  #      upload_artifact: true
  #      matrix: ${{ needs.params.outputs.matrix_arch }}
  #      artifact_prefix: ${{ needs.configure.outputs.artifact_prefix }}
  #      artifact_curr_name_add_version: false
  #      pull_base_image: true
  #      stage: builder
  #      stage_prev: ''

  # -----------------------------------------------------------------------------------------------
  # (4/8) Build & Test base
  # -----------------------------------------------------------------------------------------------
  build-base:
    needs:
      - configure
    uses: devilbox/github-actions/.github/workflows/docker-multistage-build.yml@master
    with:
      has_refs: ${{ needs.configure.outputs.has_refs == 'true' }}
      run_tests: false
      upload_artifact: true
      matrix: ${{ needs.configure.outputs.matrix_build }}
      artifact_prefix: ${{ needs.configure.outputs.artifact_prefix }}
      artifact_prev_name_add_version: true
      pull_base_image: true
      stage: base
      stage_prev: ''

  # -----------------------------------------------------------------------------------------------
  # (4/8) Build & Test base
  # -----------------------------------------------------------------------------------------------
  build-tools:
    needs:
      - configure
      - build-base
    uses: devilbox/github-actions/.github/workflows/docker-multistage-build.yml@master
    with:
      has_refs: ${{ needs.configure.outputs.has_refs == 'true' }}
      run_tests: false
      upload_artifact: true
      matrix: ${{ needs.configure.outputs.matrix_build }}
      artifact_prefix: ${{ needs.configure.outputs.artifact_prefix }}
      artifact_prev_name_add_version: true
      pull_base_image: true
      stage: tools
      stage_prev: base





  # (2/2) Build
  #  docker:
  #    needs: [params]
  #    uses: devilbox/github-actions/.github/workflows/docker-name-version-flavour-arch.yml@master
  #    with:
  #      enabled: true
  #      can_deploy: ${{ github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/') || startsWith(github.ref, 'refs/heads/release-') }}
  #      matrix: ${{ needs.params.outputs.matrix }}
  #      refs: ${{ needs.params.outputs.refs }}
  #    secrets:
  #      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
  #      dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}
  #
