---

# -------------------------------------------------------------------------------------------------
# Job Name
# -------------------------------------------------------------------------------------------------
name: params

#          "latest",
#          "2.11",
#          "2.10",
#          "2.9",
#          "2.8"
#          Helm (and more)
#      "3.10",
#      "3.0",
#      "2.16"

# -------------------------------------------------------------------------------------------------
# Custom Variables
# -------------------------------------------------------------------------------------------------
env:
  VERSIONS: >-
    [
      {
        "NAME": "ansible",
        "VERSION": [
          "latest",
          "2.8"
        ],
        "KOPS": [
          "1.25",
          "1.14"
        ],
        "HELM": [
          "3.10",
          "3.0"
        ],
        "FLAVOUR": ["default"],
        "ARCH":    ["linux/amd64"]
      }
    ]


# -------------------------------------------------------------------------------------------------
# When to run
# -------------------------------------------------------------------------------------------------
on:
  workflow_call:
    outputs:
      versions:
        description: "The determined Ansible version matrix"
        value: ${{ jobs.params.outputs.versions }}
      refs:
        description: "The determined git ref matrix (only during scheduled run)"
        value: ${{ jobs.params.outputs.refs }}

jobs:
  params:
    runs-on: ubuntu-latest

    outputs:
      versions: ${{ steps.set-matrix.outputs.versions }}
      refs: ${{ steps.set-refs.outputs.refs }}

    steps:
      - name: "[Set-Output] Matrix"
        id: set-matrix
        run: |

          VERSIONS="$( echo '${{ env.VERSIONS }}' | jq -M -c )"
          echo "versions=${VERSIONS}" >> $GITHUB_OUTPUT

      - name: "[Set-Output] Matrix 'Refs' (master branch and latest tag)"
        id: set-refs
        uses: cytopia/git-ref-matrix-action@v0.1.12
        with:
          repository_default_branch: master
          branches: master
          num_latest_tags: 0
        if: github.event_name == 'schedule'

      - name: "[DEBUG] Show settings'"
        run: |
          echo 'Versions'
          echo '--------------------'
          echo '${{ steps.set-matrix.outputs.versions }}'
          echo

          echo 'Refs'
          echo '--------------------'
          echo '${{ steps.set-matrix-refs.outputs.refs }}'
          echo
